services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис авторизации
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    env_file: ./auth-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./auth-service:/app
      - ./common:/app/common
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8000"

  # Сервис корзины
  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    env_file: ./cart-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./cart-service:/app
      - ./common:/app/common
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8002:8000"

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    env_file: ./product-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./product-service:/app
      - ./common:/app/common
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8003:8000"

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    env_file: ./order-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./order-service:/app
      - ./common:/app/common
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8004:8000"

  product-seed:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    env_file: ./product-service/.env
    command: python seed_db.py
    volumes:
      - ./product-service:/app
      - ./common:/app/common
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
